version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Set up DPKG-based dependencies"
          command: |
            sudo apt update;
            # Set up Java
            sudo apt install -y openjdk-17-jdk nodejs;
            # Set up NodeJS
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash;
            \. "$HOME/.nvm/nvm.sh";
            nvm install 23;
            # Set up Android SDK
            sudo apt install -y android-sdk;
      - run:
          name: "Install NPM-based dependencies"
          command: |
            sudo apt install -y npm;
            sudo npm install -g npx;
            # Set up build tools
            sudo npm i -g bundletools;
      - run:
          name: "Install Runtime & Compilation Dependencies"
          command: "npm i"
      - run:
          name: "Compile HCB Mobile - PREBUILD"
          command: "npx expo prebuild"
      - run:
          name: "Compile HCB Mobile - ARTIFACTS"
          command: "npx react-native build-android --mode=release"
      - run:
          name: "Unpack Keystore"
          command: "echo ($KEYSTORE) | base64 -d > uploadkey.keystore"
      - run:
          name: "Extract and sign APK"
          command: 'bundletool build-apks --bundle=android/app/build/outputs/bundle/release/app-release.aab --outputs=out.apks--mode=universal --ks uploadkey.keystore --ks-key-alias primary-lilylab --ks-pass=pass:$SIGNING_KEY_DECRYPTOR'

      - store_artifacts:
          path: out.apks
          name: out.zip

workflows:
  android-build:
    jobs:
      - say-hello