version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run:
          name: "Set up DPKG-based dependencies"
          command: |
            sudo apt update;
            # Set up Java
            sudo apt install -y openjdk-17-jdk nodejs;
            # Set up Android SDK
            sudo apt install -y android-sdk;
      - run:
          name: "Install sdkmanager & Accept Licenses"
          command: |
            echo "
              wget https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip;
              unzip commandlinetools-linux-6609375_latest.zip -d cmdline-tools;
              mv cmdline-tools /usr/lib/android-sdk/" | sudo bash; yes | sudo /usr/lib/android-sdk/cmdline-tools/tools/bin/sdkmanager --licenses
      - run:
          name: "Install Runtime & Compilation Dependencies"
          command: "npm i"
      - run:
          name: "Compile HCB Mobile - PREBUILD"
          command: "npx expo prebuild"
      - run:
          name: "Compile HCB Mobile - ARTIFACTS"
          command: "./gradlew assembleRelease"
          working_directory: "android"
      - store_artifacts:
          path: android/app/build/outputs/apk/release/app-release.apk
          name: release.apk

workflows:
  android-build:
    jobs:
      - say-hello
